# -*- coding: utf-8 -*-
"""Customer Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lzAqtTK5v1jmj8XWEMnlKFA-uCAHN1b
"""

import pandas as pd
path = r"C:\Users\NIHAL-PC\Downloads\Online Retail.xlsx"
data = pd.read_excel(path)
df = pd.DataFrame(data)
df.head()

#ETL

#Checking info of the df shape , null valuea and dtypes
print(df.info())

#Dropping null values in Customer ID column
df = df.dropna(subset=["CustomerID"])

#Feature creation

df['Total Amount'] = df['Quantity']*df['UnitPrice']

# Pre Cluster Analysis

#Total Bills generated
print(" * Total Bills generated ",df.groupby('InvoiceNo').ngroups)

#Total Cancelled Bills
print(" * Total Cancelled Bills",df["InvoiceNo"].str.startswith("C").sum())


#Country with highest Sales
print("")
print(" * Country with highest Sales")
print("")
country_sales = df.groupby("Country")["Total Amount"].sum().sort_values(ascending=False)
print(country_sales.head(10))


#Country with highest shopping
print("")
print(" * Country with highest shopping")
print("")
country_shopping = df.groupby("Country")["InvoiceNo"].nunique().sort_values(ascending = False)
print(country_shopping.head(10))

#Products in Demand
print("")
Total_products = df.groupby('StockCode').ngroups
print(" * Total Products",Total_products)
in_demand = df.groupby(['StockCode','Description'])['StockCode'].count().sort_values(ascending = False)
print(" * In Demand products",in_demand.head(20))


#High Value products
exclude = ["POSTAGE", "DOTCOM POSTAGE", "Discount", "Manual","C2","CRUK","D","DOT","M","POST","BANK CHARGES","PADS"]
product_df = df[~df["StockCode"].isin(exclude)]
print("")
high = product_df.groupby('StockCode')['UnitPrice'].mean().sort_values(ascending=False)
print(" * High Value Products",high.head(20))

import plotly.express as px

##1. Country with Highest Sales

country_sales = (
    df.groupby("Country")["Total Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

fig = px.bar(
    country_sales,
    x="Country",
    y="Total Amount",
    title="Top 10 Countries by Sales",
    color = "Country",
    text_auto=".2s",
)

fig.update_layout(
    xaxis_title="Country",
    yaxis_title="Total Sales",
    template="seaborn"
)

fig.show()

# 2. Country with Highest Shopping
# (Number of Unique Bills)


country_shopping = (
    df.groupby("Country")["InvoiceNo"]
    .nunique()
    .sort_values(ascending=False)
    .head(10)
    .reset_index(name="Orders")
)

fig = px.bar(
    country_shopping,
    x="Country",
    y="Orders",
    title="Top 10 Countries by Number of Orders",
    color = "Country",
    text_auto=True,
)

fig.update_layout(
    xaxis_title="Country",
    yaxis_title="No. of Orders",
    template="seaborn"
)

fig.show()

# 3. Most Demanded Products

in_demand = (
    df.groupby(["StockCode", "Description"])
      .size()
      .reset_index(name="Frequency")
      .sort_values("Frequency", ascending=False)
      .head(20)
)

fig = px.bar(
    in_demand,
    x="Description",
    y="Frequency",
    title="Top 20 Most Demanded Products",
    color = "Description",
    text_auto=True,
)

fig.update_layout(
    xaxis_title="Product",
    yaxis_title="Times Purchased",
    xaxis_tickangle=-45,
    template="seaborn"
)

fig.show()

# 4. Highest Value Products


exclude = [
    "POSTAGE","DOTCOM POSTAGE","Discount","Manual",
    "C2","CRUK","D","DOT","M","POST",
    "BANK CHARGES","PADS"
]

product_df = df[~df["StockCode"].isin(exclude)]

high = (
    product_df.groupby(["StockCode","Description"])["UnitPrice"]
    .mean()
    .sort_values(ascending=False)
    .head(20)
    .reset_index()
)

fig = px.bar(
    high,
    x="Description",
    y="UnitPrice",
    title="Top 20 Highest Value Products",
    color = "Description",
    text_auto=".2f",
)

fig.update_layout(
    xaxis_title="Product",
    yaxis_title="Average Unit Price",
    xaxis_tickangle=-60,
    template="plotly_white"
)

fig.show()

#Making RFM for customer segmentation

#Recency
# Convert to datetime
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
# Reference date (usually 1 day after the last transaction)
analysis_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)
# Get last purchase date for each customer
rfm = df[df["Quantity"] > 0].groupby("CustomerID")["InvoiceDate"].max().reset_index()
# Calculate recency
rfm["Recency"] = (analysis_date - rfm["InvoiceDate"]).dt.days
rfm = rfm[["CustomerID", "Recency"]]


#Frequency
# Frequency
frequency = df[df["Quantity"] > 0].groupby("CustomerID")["InvoiceNo"].nunique().reset_index()
frequency.rename(columns={"InvoiceNo": "Frequency"}, inplace=True)
rfm = rfm.merge(frequency, on="CustomerID", how="left")



#Monetary
monetary = df[df["Quantity"] > 0].groupby("CustomerID")["Total Amount"].sum().reset_index()
monetary.rename(columns={"Total Amount": "Monetary"}, inplace=True)
rfm = rfm.merge(monetary, on="CustomerID", how="left")


print(rfm)

#Scaling
from sklearn.preprocessing import StandardScaler
rfm_features = rfm[["Recency", "Frequency", "Monetary"]]
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm_features)

#SAve
import pickle
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

#Elbow method for optimim k

from sklearn.cluster import KMeans
import plotly.express as px

wcss = []

for k in range(1, 11):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(rfm_scaled)
    wcss.append(kmeans.inertia_)

# Create dataframe for plotting
elbow_df = pd.DataFrame({
    "K": range(1, 11),
    "WCSS": wcss
})

fig = px.line(
    elbow_df,
    x="K",
    y="WCSS",
    markers=True,
    title="Elbow Method for Optimal K"
)

fig.update_layout(
    xaxis_title="Number of Clusters (K)",
    yaxis_title="WCSS",
    template="seaborn"
)

fig.show()

from sklearn.cluster import KMeans
kmeans = KMeans(
  n_clusters = 4,
  random_state=42,
  n_init=10
)
rfm["Cluster"] = kmeans.fit_predict(rfm_scaled)
print(rfm.head())

import pickle
with open("kmeans.pkl", "wb") as f:
    pickle.dump(kmeans, f)

#Post cluster analysis

import plotly.express as px

fig = px.scatter(
    rfm,
    x="Recency",
    y="Monetary",
    color="Cluster",
    title="Customer Segments",
    hover_data=["CustomerID", "Frequency"],
    template = "plotly_dark"
)

fig.show()

cluster_summary = rfm.groupby("Cluster").agg({
    "Recency": "mean",
    "Frequency": "mean",
    "Monetary": "mean"
}).round(2)

print(cluster_summary)

#Classification

Cluster 2 (Champions)
Purchased very recently (Recency = 7 days)
Extremely high frequency
Extremely high spending

Cluster 0 (Loyal Customers)
Recent purchases
Good frequency
High spending

Cluster 3 (Potential Customers)
Moderate recency
Low frequency
Low spending

Cluster 1 (Lost / At-Risk)
Haven't purchased for a long time
Rarely purchase
Very low spending

cluster_names = {
    0: "Loyal Customers",
    1: "Lost Customers",
    2: "VIP",
    3: "Potential Customers"
}

rfm["Segment"] = rfm["Cluster"].map(cluster_names)

rfm["Segment"].value_counts()

#Recency Vs Monetary

import plotly.express as px

fig = px.scatter(
    rfm,
    x="Frequency",
    y="Monetary",
    color="Segment",
    hover_data=["CustomerID", "Recency"],
    title="Customer Segmentation using RFM + K-Means"
)

fig.show()

#Check Segment Distribution
rfm["Segment"].value_counts()
import plotly.express as px

segment_count = rfm["Segment"].value_counts().reset_index()
segment_count.columns = ["Segment", "Customers"]

fig = px.pie(
    segment_count,
    names="Segment",
    values="Customers",
    title="Customer Segment Distribution",
    template = "seaborn"

)
fig.update_layout(
  width = 1000,
  height = 700

)
fig.show()

#Segment Summary
segment_summary = rfm.groupby("Segment")[["Recency","Frequency","Monetary"]].mean().round(2)

print(segment_summary)

#New Customer category identification
import pickle
# Load scaler
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)
# Load kmeans model
with open("kmeans.pkl", "rb") as f:
    kmeans = pickle.load(f)

R = int(input("Enter Recency (days since last purchase): "))
F = int(input("Enter Frequency (number of orders): "))
M = float(input("Enter Monetary value (total spending): "))

new_customer = pd.DataFrame(
    [[R, F, M]],
    columns=["Recency", "Frequency", "Monetary"]
)

# Scale
new_customer_scaled = scaler.transform(new_customer)

# Predict cluster
segment = kmeans.predict(new_customer_scaled)

print("Cluster:", segment[0])

cluster_names = {
    0: "Loyal Customers",
    1: "Lost Customers",
    2: "Champions",
    3: "Regular Customers"
}
print("Segment :" ,cluster_names[segment[0]])